os: linux
language: node_js

# we want to install lyne-components @ latest version. if we dont's
# skip install, travis take the dependency from cache.
install: skip

jobs:

  include:
    - stage: build and deploy
      if: branch = master
      script:

        # install dependencies
        - npm install

        # lint
        - npm run lint || travis_terminate 1

        # Make production build
        - DATO_API_TOKEN=$DATO_API_TOKEN npm run build

      after_success:

        # Deploy to netlify
        - netlify deploy --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir ./dist/

        # run semantic release
        - npm run semantic-release

        # Inform Dato CMS on successfull build&deploy
        - |
          curl -n -X POST https://webhooks.datocms.com/c11ab978efe05ef897a2/deploy-results \
          -H 'Content-Type: application/json' \
          -d '{ "status": "success" }'

      # Inform Dato CMS of failure of build
      after_failure:
        - |
          curl -n -X POST https://webhooks.datocms.com/c11ab978efe05ef897a2/deploy-results \
          -H 'Content-Type: application/json' \
          -d '{ "status": "error" }'
