os: linux
language: node_js
cache:
  npm: false
jobs:
  include:
    - stage: build and deploy
      if: branch = master
      script:

        # Make production build
        - DATO_API_TOKEN=$DATO_API_TOKEN npm run build

      after_success:

        # install netlify-cli. We send stdout/stderr to /dev/null since we're not
        # interested in the output from netlify-cli
        - npm install netlify-cli -g > "/dev/null" 2>&1

        # Deploy to netlify
        - netlify deploy --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir ./dist/

        # Inform Dato CMS on successfull build&deploy
        - |
          curl -n -X POST https://webhooks.datocms.com/c11ab978efe05ef897a2/deploy-results \
          -H 'Content-Type: application/json' \
          -d '{ "status": "success" }'

      # Inform Dato CMS of failure of build
      after_failure:
        - |
          curl -n -X POST https://webhooks.datocms.com/c11ab978efe05ef897a2/deploy-results \
          -H 'Content-Type: application/json' \
          -d '{ "status": "error" }'
