os: linux
language: node_js

jobs:
  include:
    - stage: build and deploy
      if: branch = master
      script:

        - npx @gridsome/cli build

        # Make production build
        - npm run build

      after_success:

        # install netlify-cli. We send stdout/stderr to /dev/null since we're not
        # interested in the output from netlify-cli
        - npm install netlify-cli -g > "/dev/null" 2>&1

        # Deploy to netlify
        - netlify deploy --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir ./dist/
